// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE8Kaw1DFmlx2ni-wL9k7pMgLAGkg2hiw',
    appId: '1:377817714566:web:83db39eb9a50a85c51a607',
    messagingSenderId: '377817714566',
    projectId: 'storage2-693a0',
    authDomain: 'storage2-693a0.firebaseapp.com',
    storageBucket: 'storage2-693a0.appspot.com',
    measurementId: 'G-0Z31N78ZEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQUCPcblk8eey2jva3ar4pO7gNnHCgq4',
    appId: '1:377817714566:android:3fc91fa1d0f9d19b51a607',
    messagingSenderId: '377817714566',
    projectId: 'storage2-693a0',
    storageBucket: 'storage2-693a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI0EjDhznl43y6V93iz6HuZbGCr7NsBQU',
    appId: '1:377817714566:ios:a5db0295b9917af151a607',
    messagingSenderId: '377817714566',
    projectId: 'storage2-693a0',
    storageBucket: 'storage2-693a0.appspot.com',
    iosBundleId: 'com.example.storage2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI0EjDhznl43y6V93iz6HuZbGCr7NsBQU',
    appId: '1:377817714566:ios:f0047220aa0a445851a607',
    messagingSenderId: '377817714566',
    projectId: 'storage2-693a0',
    storageBucket: 'storage2-693a0.appspot.com',
    iosBundleId: 'com.example.storage2.RunnerTests',
  );
}
